image: golang:latest

stages:
  - ğŸ³publish
  - ğŸ§ªtests
  - ğŸ“¦deploy

variables:
  DOCKER_TLS_CERTDIR: ""
  GO_EXAMPLE_IMAGE: $CI_REGISTRY_IMAGE:go_example_$CI_COMMIT_SHORT_SHA
  GO_EXAMPLE_LATEST: $CI_REGISTRY_IMAGE:go_example_latest

test:
  stage: ğŸ§ªtests
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)
  artifacts:
    paths:
      - public/ğŸ§ªtests.svg
publish:
  stage: ğŸ³publish
  image: docker:20.10.16-dind
  services:
    - docker:20.10.16-dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin
  script:
    - docker build -t $GO_EXAMPLE_LATEST -t $GO_EXAMPLE_IMAGE .
    - docker push $GO_EXAMPLE_LATEST
    - docker push $GO_EXAMPLE_IMAGE
  tags:
    - docker
  only:
    - main
  artifacts:
    paths:
      - public/ğŸ³publish.svg
deploy:
  stage: ğŸ“¦deploy
  script: echo "Define your deployment script!"
  environment: production
  artifacts:
    paths:
      - public/ğŸ“¦deploy.svg
